modules/master_settings/modules/core/controllers/UsertypeController.php
<?php

namespace app\modules\master_settings\modules\core\controllers;

use Yii;
use app\modules\master_settings\modules\core\models\Usertype;
use app\modules\master_settings\modules\core\models\UsertypeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\AuthItem;
use app\models\AuthAssignment;
use app\controllers\BaseController;

/**
 * UsertypeController implements the CRUD actions for Usertype model.
 */
class UsertypeController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Usertype models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsertypeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Usertype model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Usertype model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Usertype();

        if ($model->load(Yii::$app->request->post())) {
             $model->created_by=Yii::$app->user->identity->id;
             $model->role=$model->title.' '.'Role';
             $model->save(false);
            return $this->redirect(['index']);
        } 
            return $this->render('create', [
                'model' => $model,
            ]);
        
    }

    /**
     * Updates an existing Usertype model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->updated_at=new \yii\db\Expression('NOW()');
            $model->updated_by=Yii::$app->user->identity->id;
            $model->save();
            return $this->redirect(['index']);
        }
            return $this->render('update', [
                'model' => $model,
            ]);
        
    }


    /**
     * Deletes an existing Usertype model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model=$this->findModel($id);
        //echo "<pre>";print_r($model);exit;
        $auth_assign=AuthAssignment::find()->where(['item_name'=>$model->role])->one();
        if($auth_assign===null){
        if($model->delete()){

            $authItem =AuthItem::find()->where(['name'=>$model->role])->one();
            if($authItem!==null){
                 $authItem->delete();
            }
        }
        }else{
            Yii::$app->session->setFlash('danger',Yii::t('app','Failed: This Role already assigned to user,You can not delete'));
            return $this->redirect(['index']);
        }

        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Usertype model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Usertype the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($key)
    {
        $id=Yii::$app->encryptor->decrypt($key);
        if (($model = Usertype::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/master_settings/modules/core/views/usertype/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;


/* @var $this yii\web\View */
/* @var $model app\models\Usertype */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usertype-form">

    <?php $form = ActiveForm::begin([
        'options' => ['class' => 'form-horizontal'],
        'id'                     => 'password-form',
        // 'enableAjaxValidation'   => true,
        // 'enableClientValidation' => false,
        'fieldConfig' => [
        'template' => "{label}\n<div class=\"col-xs-8\">{input}{error}</div>",
        'labelOptions' => ['class' => 'col-xs-4 control-label'],
        ],
    ]); ?>
        <div class="row">
            <h4 class="col-md-8" >
               <i class="lg fa fa-info"></i>
               <strong> User Type</strong>
            </h4>
            <div class="col-md-12 " style="height: 10px;"></div>
            <div class="form-column col-md-6" > 

    <?= $form->field($model, 'title')->textInput(['maxlength' => 50]) ?>

    
    </div>
        </div>

     <div class="form-actions">
                <?= Html::submitButton($model->isNewRecord ? Yii::t('app', '<i class="ace-icon fa fa-plus"> Create</i>') : Yii::t('app', '<i class="ace-icon fa fa-pencil"> Update</i>'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

                <?= Html::a('<i class="ace-icon fa fa-remove"> Cancel</i>', ['usertype/index'], ['class'=>'btn btn-danger']) ?>

                <?php if ($model->isNewRecord): ?>
                <button type="reset" class="btn btn-info">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    Reset
                </button>
                <?php endif ?>
            </div>

    <?php ActiveForm::end(); ?>

</div>



                

modules/master_settings/modules/core/views/usertype/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsertypeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usertype-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'role') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'is_delete') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/master_settings/modules/core/views/usertype/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Usertype */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Usertype',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Usertypes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usertype-create">

 <div class="grey panel panel-info">
    <div class="panel-heading">
    	  <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
     </div>
    <div class="panel-body">
     
        <div class="col-lg-12">
          
<?= $this->render('_form', [
        'model' => $model,
       
        
        
    ]) ?>
</div>
</div>
</div>
</div>

modules/master_settings/modules/core/views/usertype/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsertypeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = Yii::t('app', 'Usertypes');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usertype-index">

  
      <div class="col-lg-12">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],


           
            'title',
            'role',
            
            
            // 'updated_at',
            // 'created_by',
            // 'updated_by',
            // 'is_delete',

            ['class' => '\kartik\grid\ActionColumn',
                                        
                  'template' => '{view}&nbsp;{delete}',
                    'buttons' => [
                         'view' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                             'title' => Yii::t('app', 'View'),
                            ]);
                        },
                        //  'update' => function ($url, $model) {
                        //         return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                        //      'title' => Yii::t('app', 'Update'),
                        //     ]);
                        // },
                        'delete' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                             'title' => Yii::t('app', 'Delete'),'data-method'=>"post",'data-confirm'=>"Are you sure you want to delete this item?",
                            ]);
                        }, 
                       
                    ],
                    'urlCreator' => function ($action, $model, $url, $index) {
                         $hash=Yii::$app->encryptor->encrypt($model->id); 
                         if ($action === 'view') {
                            return Url::to(['usertype/view','id'=>$hash]);
                         }else if($action === 'delete'){
                          return Url::to(['usertype/delete','id'=>$hash]);
                         }
                    },
            ],

        ],
         'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="white fa fa-users "></i> UserType </h3>',
            'type'=>'primary',
            'before'=>Html::a(Yii::t('app', '<i class="glyphicon glyphicon-plus"></i> Create {modelClass}', ['modelClass' => 'UserType',]), ['create'], ['class' => 'btn btn-primary']) ,
            'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Grid', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>true,
            'pager'=>false
            ],
            'toolbar' => [
              '{export}'
              ],
            'exportConfig' => [
            GridView::HTML =>[],
            //  GridView::PDF =>[],
            GridView::TEXT => [],
            GridView::EXCEL => [],
            ]
    ]); ?>

</div>

</div>

modules/master_settings/modules/core/views/usertype/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usertype */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Usertype',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Usertypes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => Yii::$app->encryptor->encrypt($model->id)]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="usertype-update">

   <div class="grey panel panel-info">
    <div class="panel-heading">
    	  <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
     </div>
    <div class="panel-body">
     
        <div class="col-lg-12">
          
<?= $this->render('_form', [
        'model' => $model,
       
        
        
    ]) ?>
</div>
</div>
</div>
</div>

modules/master_settings/modules/core/views/usertype/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Usertype */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Usertypes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usertype-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => Yii::$app->encryptor->encrypt($model->id)], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => Yii::$app->encryptor->encrypt($model->id)], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'title',
            'role',
            
            // 'status',
            // 'created_at',
            // 'updated_at',
            // 'created_by',
            // 'updated_by',
            // 'is_delete',
        ],
    ]) ?>

</div>