controllers/RegisterController.php
<?php 
namespace app\controllers;

use Yii;
use app\modules\user_management\modules\core\models\User;
use app\models\Registeration;
use yii\web\Response;
use yii\base\Model;
use yii\widgets\ActiveForm;
use yii\web\Controller;
use app\modules\user_management\modules\core\models\Token;
use app\models\Usertype;
use app\models\Password;
use app\models\ResendForm;
use app\models\RecoveryForm;
use yii\web\NotFoundHttpException;

class RegisterController extends Controller
{   
    public function actions()
    {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    /**
     * Register user's account. If creates user account successful and shows success message. Otherwise
     * shows error message.
    */
    public function actionRegister()
    {
        $model = \Yii::createObject([
            'class'    => Registeration::className(),
        ]);   
        $this->performAjaxValidation($model);
          if ($model->load(Yii::$app->request->post())){
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try {
               // echo "<pre>"; print_r(Yii::$app->request->post()); exit;
                $model->register();
                $transaction->commit();
              \Yii::$app->session->setFlash('success', \Yii::t('app', 'A link to complete your registration has been sent to your email '.$model->email.''));
              
                return $this->redirect(['site/login']);
        } catch (Exception $e) {
                $transaction->rollBack();
                return $this->redirect(['site/login']);
                Yii::$app->session->setFlash('danger',Yii::t('app','Failed: Some Technical Error. Try again'));
            }
        }
        return $this->render('register', [
            'model'  => $model,
            
        ]);
    }

    /**
     * Confirms user's account. If confirmation was successful logs the user and shows success message. Otherwise
     * shows error message.
     * @param  integer $id
     * @param  string  $code
     * @return string
     * @throws \yii\web\HttpException
     */
    public function actionConfirm($id, $code)
    {
        $user = User::findUserById($id);
         $model=new Password();
        if ($user === null) {
            throw new NotFoundHttpException;
        }
        $status=$user->attemptConfirmation($code);
        if($status===true){
            return $this->redirect(['register/setting','id'=>Yii::$app->encryptor->encrypt($id)]);  
        }else{
             return $this->redirect(['site/login']);
        }
            
    }


    /**
     * Displays page where user can request new confirmation token. If resending was successful, displays message.
     * @return string
     * @throws \yii\web\HttpException
     */
    public function actionResend()
    {
        $model = \Yii::createObject(ResendForm::className());

        $this->performAjaxValidation($model);
        if ($model->load(\Yii::$app->request->post()) && $model->resend()) {
            return $this->redirect(['site/login']);
        }

         return $this->render('resend', [
            'model'  => $model,
           
        ]);
    }

    /**
     * Shows page where user can request password recovery.
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionRequest()
    {

        $model = \Yii::createObject([
            'class'    => RecoveryForm::className(),
            'scenario' => 'request',
        ]);
        $this->performAjaxValidation($model);

        if ($model->load(\Yii::$app->request->post()) && $model->sendRecoveryMessage()) {
            return $this->redirect(['site/login']);
        }

        return $this->render('request', [
            'model' => $model,
        ]);
    }

     /**
     * Displays page where user can reset password.
     * @param  integer $id
     * @param  string  $code
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionReset($id, $code)
    {
        /** @var Token $token */
         $token = Token::find()->where([
           'user_id' => $id,
            'code'    => $code,
            'type'    => Token::TYPE_RECOVERY,
        ])->one();

        if ($token === null || $token->isExpired ) {
            \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Recovery link is invalid or expired. Please try requesting a new one.'));
            return $this->redirect(['site/login']);
        }

        $model = \Yii::createObject([
            'class'    => RecoveryForm::className(),
            'scenario' => 'reset',
        ]);

        $this->performAjaxValidation($model);

        if ($model->load(\Yii::$app->getRequest()->post()) && $model->resetPassword($token,$token->user_id)) {
            return $this->redirect(['site/login']);      
           
        }

        return $this->render('reset', [
            'model' => $model,
        ]);
    }

    /**
     * Performs ajax validation.
     * @param Model $model
     * @throws \yii\base\ExitException
     */
    protected function performAjaxValidation(Model $model)
    {
        
        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            echo json_encode(ActiveForm::validate($model));
            \Yii::$app->end();
        }
    }

    public function actionSetting($id)
    {   
        $model=new Password();
        $user = User::findUserById(Yii::$app->encryptor->decrypt($id));
        if ($user === null) {
            throw new NotFoundHttpException;
        }
        $this->performAjaxValidation($model); 
        if ($model->load(Yii::$app->request->post()))
        {
            $model->savePassword($user->id);
            Yii::$app->session->setFlash('success','Password has been set successfully...');
            //Yii::$app->user->logout(false);
            return $this->goHome();
        }
        
        return $this->render('setPassword', [
         'model' => $model,
          
        ]);
    
    }

     /**
     * Registerform get register form
     * @return form
     * @param null
     * @author AJ
     */
  
    public function successCallback($client)
    {   
        $attributes = $client->getUserAttributes();
        if($attributes!==null){
          User::setLoginOrRegister($attributes,$client->id);
        }else{
          return $this->redirect(['site/login']);
           \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Technical Error ...Please try Again or Contact to our support Team'));
        }
       
    }

 
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\base\Model;
use yii\widgets\ActiveForm;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SchoolImage;
use yii\authclient\AuthAction;
use yii\helpers\Url;
use app\models\Registeration;
use app\models\TblTree;
use app\models\Permission;
use app\modules\user_management\modules\core\models\User;
use app\modules\master_settings\modules\core\models\Usertype;
use app\modules\master_settings\modules\core\models\Gender;
use Aws\S3\S3Client;
use yii\web\UploadedFile;
use yii\helpers\Json ;
use yii\web\NotFoundHttpException;
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
         if (!\Yii::$app->user->isGuest){
         
       switch (Yii::$app->user->identity->user_type) {

                 case Usertype::SUPERADMIN:
                  
                  return $this->render('superadmin_dashboard.php');
                  break;

                  case Usertype::ADVISOR:
                  
                  return $this->render('advisor_dashboard.php');
                  break;
                   case Usertype::CUSTOMER:
                  
                  return $this->render('customer_dashboard.php');
                  break;
                 default:
                 return $this->redirect(['site/login']);
                 break;
            }
       }else{
         return $this->redirect(['site/login']);
       }

    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $modelContact = new ContactForm();
        $model = new LoginForm();
        $modelRegister = \Yii::createObject([
            'class'    => Registeration::className(),
        ]); 
        $this->performAjaxValidation($model);

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        
        return $this->render('login', [
            'model' => $model,
          //  'modelContact' => $modelContact,
          //  'modelRegister' => $modelRegister
        ]);
    }
   
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['site/index']);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $modelContact = new ContactForm();
        if ($modelContact->load(Yii::$app->request->post())) {
            if($modelContact->save(false)){
              return 'message'; 
            }
        }
        return $this->render('contact', [
            'modelContact' => $modelContact,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

       /**
     * Performs ajax validation.
     * @param Model $model
     * @throws \yii\base\ExitException
     */
    protected function performAjaxValidation(Model $model)
    {
        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            echo json_encode(ActiveForm::validate($model));
            \Yii::$app->end();
        }
    }

     /**
     * Registerform get register form
     * @return form
     * @param null
     * @author RG
     */
  
    public function successCallback($client)
    {   
        $attributes = $client->getUserAttributes();
        if($attributes!==null){
          User::setLoginOrRegister($attributes);
        }else{
          return $this->redirect(['site/login']);
           \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Technical Error ...Please try Again or Contact to our support Team'));
        }
             
    }


    
    public function actionLockScreen($url=null)
    {
   
       // if(isset(Yii::$app->user->identity->email)){
            $model = new LoginForm(); 
            $model->login = Yii::$app->user->identity->email;
             //Yii::$app->user->logout();    //set default value 
            return $this->renderAjax('lockScreen', [
                'model' => $model,
                //'previous'=>$url
            ]);  
        //}
            //   else{
            //return $this->redirect(['login']);
       // }
    }

     public function actionGetFiles($id=0){
       // echo $id;exit;
        $bredcrumbs=[];
        $data=[];
        $find=TblTree::find()->orderBy(['type'=>SORT_DESC])->where(['user_id'=>Yii::$app->user->identity->id])->andFilterWhere(['parent'=>$id])->asArray()->all();
    
        $data['list']=$find;
        $data['id']=$id;
       echo json_encode($data); exit;
    }

    public function actionGetBackFiles($id=0){
        $bredcrumbs=[];
        $data=[];
        $findParent=TblTree::find()->orderBy(['order_by'=>SORT_ASC])->where(['user_id'=>Yii::$app->user->identity->id])->andFilterWhere(['id'=>$id])->asArray()->one();
        //echo "<pre>"; print_r($findParent); exit;
        $findAll=TblTree::find()->orderBy(['order_by'=>SORT_ASC])->where(['user_id'=>Yii::$app->user->identity->id])->andFilterWhere(['parent'=>$findParent['parent'],'lvl'=>$findParent['lvl']])->asArray()->all();
     
        $data['list']=$findAll;
        $data['id']=$findParent['parent'];
       echo json_encode($data); exit;
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
     /**
     * actionUploadform render the view for to modal with ajax
     */
    public function actionCreateFolder()
    {    
        $model= new TblTree();
        if ($model->load(Yii::$app->request->post())){
          $response=[];
            $id=$model->id; 
            //find user has any root folder or not or it is 0 no parent or first folder
            if($id==0){
              $findParent=TblTree::find()->orderBy(['id'=>SORT_DESC])->where(['user_id'=>Yii::$app->user->identity->id,'type'=>'folder'])->andFilterWhere(['parent'=>$id])->asArray()->one();
              if(!empty($findParent)){
                $order_by=$findParent['order_by']+1;
              }else{
                $order_by=1;
              }  
              $lvl=0;
              $parent=0;
              
              $path=$model->name.'-'.Yii::$app->user->identity->id.'/';
              //user has already one folder then else will call
            }else{
              //find its parent folder using parent order by id asc order
              $findParent=TblTree::find()->orderBy(['id'=>SORT_DESC])->where(['user_id'=>Yii::$app->user->identity->id,'type'=>'folder'])->andFilterWhere(['parent'=>$id])->asArray()->one();
           
                //if no child node found
                if(empty($findParent)){
                
                    $data=TblTree::find()->orderBy(['id'=>SORT_ASC])->where(['user_id'=>Yii::$app->user->identity->id,'type'=>'folder'])->andFilterWhere(['id'=>$id])->asArray()->one();
                    $lvl=$data['lvl']+1;
                    $parent=$id;
                    $order_by=1;
                    $path=$data['path'].$model->name.'/';
                //if child node found
                }else{

                    $data=TblTree::find()->where(['user_id'=>Yii::$app->user->identity->id,'type'=>'folder'])->andFilterWhere(['id'=>$id])->asArray()->one();
                    $lvl=$findParent['lvl'];
                    $parent=$findParent['parent'];
                    $order_by=$findParent['order_by']+1;
                    $path=$data['path'].$model->name.'/';
                }
              } 
              $model->id=null;
              $model->lvl=$lvl;     
              $model->order_by=$order_by; 
              $model->parent=$parent; 
              $model->type='folder'; 
              $model->path=$path; 
              $model->user_id=Yii::$app->user->identity->id;
              $model->name=$model->name;
          
              if($model->save(false)){
                //config
                $s3 = new S3Client([
                    'version'     => 'latest',
                    'region'      => 'us-west-2',
                    //'version' => '2012-10-17', 
                    'bucket'=>'llp-arkenea',
                    'credentials' => [
                        'key'    => 'AKIAIOEMNY2ANX7KRBKA',

views/site/advisor_dashboard.php
<?php
echo "advisor dashboard";
?>

views/site/createFolder.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use kartik\datecontrol\DateControl;
use app\assets\CustomerAsset;
CustomerAsset::register($this);
?>

   <div class="upload-form">
  <?php $form = ActiveForm::begin([
    'id'=>'folder-form',
        //'action'=>['upload-invoice'],
        //'enableAjaxValidation'=>false,
        'options' => ['class' => 'form-smart',
        'enctype' => 'multipart/form-data'
        ],

        'fieldConfig' => [
          'template' => "{label}\n<div class=\"col-xs-8\">{input}{error}</div>",
          'labelOptions' => ['class' => 'col-xs-2 control-label'],
        ],
        ]); ?>
  <div class="panel panel-default">

      <div class="panel-default"><!-- widgetBody -->

      <div class="panel-heading">

        <span class="panel-title-address">Folder create</span>

        <div class="clearfix"></div>

      </div>

      <div class="panel-body">

        <div class="row">     
        <div class="col-md-8">                      
                    <?= $form->field($model, 'name', [
                        'template' => "\n{input}\n{hint}\n{error}"
                        ])->textInput(['placeholder'=>Yii::t('app', 'Enter Title Here')]);  ?>
                         <?php echo $form->field($model, 'id')->hiddenInput()->label(false);?>
        </div> 
     
                             </div>

      </div>

      </div>
  </div>
           <div class="form-actions">
                          <div class="row">
                            <div class="col-md-7 pull-right">
                              <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' =>  'btn btn-success','id' =>'add-btn']) ?>
                              <?= Html::submitButton(Yii::t('app', 'Remove'), ['class' =>  'btn btn-warning btn-hide','id' => 'rmv-hide']) ?>
                              <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-remove bigger-110"></i>Close</button>
                            </div>
                          </div>
                        </div>
              <?php ActiveForm::end(); ?>
  </div>

<script type="text/javascript">
    
 $('#folder-form').on('beforeSubmit', function(e) {
alert('processing');
    var form = $(this);

    var formData = form.serialize();

    $.ajax({

        url: form.attr("action"),

        type: form.attr("method"),

        data: formData,

        success: function (data) {
   
              $('#draggable').modal('toggle');
             $.getScript("js/customer.js" ) 
  .done(function( script, textStatus ) {
   // alert( textStatus );
  })
  .fail(function( jqxhr, settings, exception ) {
   // alert(exception);
     getFolders();
    $( "div.log" ).text( "Triggered ajaxError handler." );
});
         
        },
        error: function () {
  
            alert("Error Please try again");
            
        }

    });

}).on('submit', function(e){

    e.preventDefault();

});



</script>

views/site/customer_dashboard.php
<?php
use kartik\tree\TreeView;
use app\models\Product;
use simialbi\yii2\elfinder\widgets\ElFinder;
use \kartik\tree\Module;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use Aws\S3\S3Client;
use app\assets\CustomerAsset;
CustomerAsset::register($this);
echo "user dashboard";

// $s3 = new S3Client([
// 'version'     => 'latest',
// 'region'      => 'us-west-2',
// //'version' => '2012-10-17', 
// 'bucket'=>'llp-arkenea',
// 'credentials' => [
//     'key'    => 'AKIAIOEMNY2ANX7KRBKA',
//     'secret' => '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',
// ],]);
// try{
//     $res=$s3->putObject(array( 
        
//                    'Bucket' => 'llp-arkenea',
//                    'Key'    => "documents"."/",
//                    'Body'   => "",
//                    'ACL'    => 'public-read'
//                   ));
//     print_r($res);
//     } catch (AwsException $e) {
//     // Display error message
//     echo $e->getMessage();
//     echo "\n";
// }exit;

// echo "<pre>"; print_r($s3);exit;
// $s3 = Yii::$app->get('s3');
// $result = $s3->get('other/image_14212_106.jpg');
// $s3 = Yii::$app->get('s3');
// //$url = $s3->commands()->getUrl('pdf.pdf')->execute();
// $imageContent = file_get_contents("https://llp-arkenea.s3.us-west-2.amazonaws.com/pdf.pdf");
// print_r($imageContent); exit;
//         file_put_contents($imageName, $imageContent);
// $signedUrl = $s3->commands()->getUrl('pdf.pdf', '+1 days')->execute();
// echo "<pre>"; print_r($signedUrl);exit;
?>
<div class="row">
    <div class="well col-md-12">
        <div class="breadcrumbs"></div>
        <div class=""> <br>
              
              <a href="#" class="btn btn-default btn-lg backBtn" data-id="0" style="visibility: hidden;" data-toggle="tooltip" title="Back"><i class="fa fa-arrow-left"></i></a>
              <a href="#" class="btn btn-default btn-lg folderBtn" data-id="0" data-toggle="tooltip" title="Create New Folder"><i class="fa fa-plus"></i></a>
             
              <a href="#" class="btn btn-default btn-lg fileBtn" data-id="0" style="visibility: hidden;" data-toggle="tooltip" title="Upload files"><i class="fa fa-upload"></i></a>
              
              
             
            </div>
        <div class="filemanager">
        <div class="breadcrumbs"></div>
        <ul class="data animated"></ul>
        <div class="nothingfound">
            <div class="nofiles"></div>
            <span>No files here.</span>
        </div>

    </div>
    </div>
</div>

views/site/customer_dashboardlist.php
<?php
use kartik\tree\TreeView;
use app\models\Product;
use simialbi\yii2\elfinder\widgets\ElFinder;
use \kartik\tree\Module;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use Aws\S3\S3Client;
use app\assets\CustomerAsset;
CustomerAsset::register($this);
echo "user dashboard";
?>
<div id="wizard" class="panel panel-default">

</div>

views/site/front_login.php
<?php

/**
 * @Author: ajkosh
 * @Date:   2018-06-13 14:29:36
 * @Last Modified by:   ajkosh
 * @Last Modified time: 2018-06-13 14:29:53
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Carousel;
use app\assets\LoginAsset;
use app\modules\settings\modules\core\models\Config;

LoginAsset::register($this);
$this->title = Yii::t('app', 'TecnicaGuru Corporate Trainiing Portal ');
?>

        <div class="row">
        
          <div class="col-lg-5 col-md-offset-4" id="down-padding">
            <div class="well no-padding">
              <?php $form = ActiveForm::begin([
                 'enableAjaxValidation'   => true,
                   'enableClientValidation' => false,
                   'id' => 'dynamic-form',
                'options' => ['class' => 'smart-form client-form'],
                
                ]);?>
                <header>
                   <img src="<?php echo \Yii::$app->request->BaseUrl?>/images/login_logo.png" class="login-img" alt="">

                </header>
                <fieldset>
                  <section>
                    
                    <label class="input"> <i class="icon-append fa fa-user"></i>
                      <?= $form->field($model, 'login', [
                        'template' => "\n{input}\n{hint}\n{error}"
                        ])->textInput(['placeholder'=>Yii::t('app', 'Email or Username')]);  ?>
                  </section>
                  <section>
                   
                      <label class="input"> <i class="icon-append fa fa-lock"></i>
                          <?= $form->field($model, 'password', [
                            'template' => "\n{input}\n{hint}\n{error}"
                            ])->passwordInput(['placeholder'=>Yii::t('app', 'Password')]);  ?>
                          <div class="note">
                            <a href="<?php  echo Url::toRoute('/register/request');?>"><?php echo  Yii::t('app', 'Forgot password?')?></a>
                          </div>
                  </section>
                          
                </fieldset>
             <footer>
                
                  <button type="submit" class="btn btn-primary">
                    <?php echo  Yii::t('app', ' Sign in   ')?>
                  </button>
                </footer>

                <?php ActiveForm::end(); ?>
            </div>
           
          </div>
          <div class=" col-lg-5 col-md-offset-4">
          <div class="well no-padding">
            <br>
              <p class="text-center">
              <?= Html::a(Yii::t('app', 'New Registration'), ['/register/register']) ?>
            </p>
            <p class="text-center">
              <?= Html::a(Yii::t('app', 'Didn\'t receive confirmation message?'), ['/register/resend']) ?>
            </p>
            <h5 class="text-center"> <?php echo  Yii::t('app', ' - Or sign in using - ')?></h5>
              <ul class="list-inline text-center">
                <li>
                  <a href="<?php echo Url::toRoute(['/site/auth','authclient'=>'google_login']);?>" class="btn btn-danger btn-circle btn-lg"><i class="fa fa-google"></i></a>
                </li>
              </ul>
</div>
         </div>
        </div>

    

views/site/lockScreen.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use app\assets\LockAsset;
LockAsset::register($this);
?>
<head>
<style type="text/css">
	

</style>
	</head>

                  <div class="logo">
					<h1 class="semi-bold"><img src="img/logo-o.png" alt=""> SmartAdmin</h1>
				</div>
				<div>
					<img src="img/avatars/sunny-big.png" alt="" width="120" height="120">
					<div>
						<h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile"></i>John Doe <small><i class="fa fa-lock text-muted"></i> &nbsp;Locked</small></h1>
						<p class="text-muted">
							<a href="mailto:simmons@smartadmin"><?php echo $model->login;?></a>
						</p>

						 <?php $form = ActiveForm::begin([
                 'enableAjaxValidation'   => true,
                   'enableClientValidation' => false,
                   'action'=>['login'],
                   'id' => 'dynamic-form',
                'options' => ['class' => 'lockscreen animated flipInY'],
                
                ]);?>
                
                          <?= $form->field($model, 'password', [
                            'template' => "\n{input}\n{hint}\n{error}"
                            ])->passwordInput(['placeholder'=>Yii::t('app', 'Password')]);  ?>
                             <?= $form->field($model, 'login', [
                        'template' => "\n{input}\n{hint}\n{error}"
                        ])->textInput(['placeholder'=>Yii::t('app', 'Email or Username')]);  ?>
                         
                 
             <footer>
                
                  <button type="submit" class="btn btn-primary">
                    <?php echo  Yii::t('app', ' Sign in   ')?>
                  </button>
                </footer>

                <?php ActiveForm::end(); ?>
						<p class="no-margin margin-top-5">
							Logged as someone else? <a href="login.html"> Click here</a>
						</p>
					</div>

				</div>
				<p class="font-xs margin-top-5">
					Copyright SmartAdmin 2014-2020.

				</p>
            
       

views/site/login.php
<?php

/**
 * @Author: ajkosh
 * @Date:   2018-06-13 14:29:36
 * @Last Modified by:   ajkosh
 * @Last Modified time: 2018-06-13 14:29:53
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Carousel;
use app\modules\settings\modules\core\models\Config;
use app\assets\LoginAsset;
LoginAsset::register($this);
$this->title = Yii::t('app', 'LLP');
?>

        <div class="row">
        
          <div class="col-lg-3 col-md-offset-4" id="down-padding">
            <div class="well no-padding">
              <?php $form = ActiveForm::begin([
                 'enableAjaxValidation'   => true,
                   'enableClientValidation' => false,
                   'id' => 'dynamic-form',
                'options' => ['class' => 'smart-form client-form'],
                
                ]);?>
                <header>
                   <img src="" class="login-img" alt="logo">

                </header>
                <fieldset>
                  <section>
                    
                    <label class="input"> <i class="icon-append fa fa-user"></i>
                      <?= $form->field($model, 'login', [
                        'template' => "\n{input}\n{hint}\n{error}"
                        ])->textInput(['placeholder'=>Yii::t('app', 'Email or Username')]);  ?>
                  </section>
                  <section>
                   
                      <label class="input"> <i class="icon-append fa fa-lock"></i>
                          <?= $form->field($model, 'password', [
                            'template' => "\n{input}\n{hint}\n{error}"
                            ])->passwordInput(['placeholder'=>Yii::t('app', 'Password')]);  ?>
                          <div class="note">
                            <a href="<?php  echo Url::toRoute('/register/request');?>"><?php echo  Yii::t('app', 'Forgot password?')?></a>
                          </div>
                  </section>
                          
                </fieldset>
             <footer>
                
                  <button type="submit" class="btn btn-primary">
                    <?php echo  Yii::t('app', ' Sign in   ')?>
                  </button>
                </footer>

                <?php ActiveForm::end(); ?>
            </div>
           
          </div>
          <div class=" col-lg-3 col-md-offset-4" style= "display: none;">
          <div class="well no-padding">
            <br>
              <p class="text-center">
              <?= Html::a(Yii::t('app', 'New Registration'), ['/register/register']) ?>
            </p>
            <p class="text-center">
              <?= Html::a(Yii::t('app', 'Didn\'t receive confirmation message?'), ['/register/resend']) ?>
            </p>
            <h5 class="text-center"> <?php echo  Yii::t('app', ' - Or sign in using - ')?></h5>
              <ul class="list-inline text-center">
                <li>
                  <a href="<?php echo Url::toRoute(['/site/auth','authclient'=>'google_login']);?>" class="btn btn-danger btn-circle btn-lg"><i class="fa fa-google"></i></a>
                </li>
              </ul>
</div>
         </div>
        </div>

    

views/site/superadmin_dashboard.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\master_settings\modules\core\models\Cities;
use app\modules\master_settings\modules\core\models\States;
?>

<?php echo 'This is current langauge' .' '.  \Yii::$app->language .' <br>  '.Yii::t('app', 'enquiry');  ?><br>
<?php echo 'This is current timezone' .' '.  \Yii::$app->timeZone .' <br>  '. (new \DateTime())->format('Y-m-d H:i:s');
echo "superadmin dashboard";

?>