modules/user_management/modules/core/models/User.php
<?php

namespace app\modules\user_management\modules\core\models;

use Yii;
use app\components\modules\ModuleActiveRecordTrait;
use app\modules\user_management\events\SampleEvent;
use app\modules\user_management\User_Management;
use app\models\BaseModel;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\base\Security;
use yii\web\IdentityInterface;
use app\modules\master_settings\modules\core\models\Usertype;
use yii\rbac\DbManager;
use yii\log\Logger;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use yii\web\Controller;
use app\models\Password;
use yii\helpers\Url;
use app\modules\master_settings\modules\core\models\Gender;
use app\modules\master_settings\modules\core\models\UserToken;
use app\modules\settings\modules\core\models\Type;


class User extends BaseModel implements IdentityInterface
{
    use ModuleActiveRecordTrait;

    public function create()
    {
        User_Management::triggerEvent(User_Management::SAMPLE_EVENT, new SampleEvent());
    }
     
    public $isNewRecord;
    public $fullName;
    public $passwd;
   
  

  
     /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
       return [

       [['confirmed_at', 'blocked_at', 'updated_by', 'status', 'created_by','flag'], 'integer'],
        [['user_type'], 'required'],
             //username rules
       ['username', 'filter', 'filter' => 'trim'],
       ['username', 'match', 'pattern' => '/^[-a-zA-Z0-9_\.@]+$/'],
       //['username', 'required'],
       ['username', 'unique',
       'message' => \Yii::t('app', 'This username has already been taken')],
       ['username', 'string', 'min' => 3, 'max' => 20],
            // email rules
       ['email', 'filter', 'filter' => 'trim'],
       ['email', 'required'],
       ['email', 'email'],
       ['email', 'unique',
       'message' => \Yii::t('app', 'This email address has already been taken')],
            
        [['first_name','last_name','gender'], 'required'],
        [['created_at', 'updated_at','user_type'],'safe'],
       
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
       return [
            'email'    => \Yii::t('app', 'Login'),
            'username' => \Yii::t('app', 'Username'),
            'password_hash' => \Yii::t('app', 'Password'),
            'email'=> Yii::t('app', 'Email'),
            'email_type' => Yii::t('app', 'Account Type'),
            'user_type' => Yii::t('app', 'User Type'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'company_name' => Yii::t('app', 'Company Name'),
            'gender' => Yii::t('app', 'Gender'),
            'mobile' => Yii::t('app', 'Mobile'),
            'city_id' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State'),
            'country_id' => Yii::t('app', 'Country'),
            'comapny_type_id' => Yii::t('app', 'Company Type'),
            'landline_off' => Yii::t('app', 'Landline(office)'),
            'landline_res' => Yii::t('app', 'Landline(resident)'),
            'access_type_id' => Yii::t('app', 'Access Type'),
            'iuser_company' => Yii::t('app', 'Companies'),
            
        ];
    }
    
   
    /**
     * @return \yii\db\ActiveQuery
     */
        public function getUserType()
        {
            return $this->hasOne(Usertype::className(), ['id' => 'user_type']);
        }
     /**
     * Finds a user by the given id.
     *
     * @param  integer     $id User id to be used on search.
     * @return models\User
     */
     public static function findUserById($id)
    {
        return static::findOne(['id' => $id]);
    }
      
    
    /**
     * @return \yii\db\ActiveQuery
     */

    /** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);

    }
    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type=null)
    {
        if (UserToken::isTokenValid($token))
        {
            // TODO: get api user
            return static::findOne(1);
        }
        throw new \yii\web\UnauthorizedHttpException('Login failed');
    }

    /**
     * Finds user by username
     *
     * @param string     $username
     * @return static|null
     */
    public static function findUserByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }


    /**
     * Finds a user by the given email.
     *
     * @param  string      $email Email to be used on search.
     * @return models\User
     */
    public static function findUserByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds a user by the given username or email.
     *
     * @param  string      $usernameOrEmail Username or email to be used on search.
     * @return models\User
     */
    public static function findUserByUsernameOrEmail($usernameOrEmail)
    {
        if (filter_var($usernameOrEmail, FILTER_VALIDATE_EMAIL)) {
            return User::findUserByEmail($usernameOrEmail);
        }

        return User::findUserByUsername($usernameOrEmail);
    }

    /**
     * Finds user by password reset token
     *
     * @param string     $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    
    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        return Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->getSecurity()->generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->getSecurity()->generateRandomKey() . '_' . time();
    }
    

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    /** EXTENSION MOVIE **/

    /**
     * Aftersave called everytime any save happen, create or update
     * Assign role to new or updated users based on user type
     * @param $insert
     * @param $changedAttributes
     * @return [boolean]
     */
    public function afterSave($insert,$changedAttributes)
    {
        $role = Usertype::findOne($this->user_type)['role'];

        $obj = (object)array('name' => $role);
       // echo "<pre>"; print_r($this->user_type); print_r($role); print_r($obj);exit;
        $r=new DbManager;

        $r->init();

        $r->revokeAll($this->id);

        $r->assign($obj, $this->id);

        if (parent::afterSave($insert,$changedAttributes)) {
            return true;
        } else {
            return false;
        }
    }

 /**
     * Generates user-friendly random password containing at least one lower case letter, one uppercase letter and one
     * digit. The remaining characters in the password are chosen at random from those three sets.
     * @see https://gist.github.com/tylerhall/521810
     * @param $length
     * @return string
     */
    public static function generate($length) {
    $str = "";
    $characters = array_merge(range('A','Z'), range('a','z'), range('0','9'));
    $max = count($characters) - 1;
    for ($i = 0; $i < $length; $i++) {
        $rand = mt_rand(0, $max);
        $str .= $characters[$rand];
    }
    return $str;
    }
      /**
     * This method attempts user confirmation. It uses finder to find token with given code and if it is expired
     * or does not exist, this method will throw exception.
     *
     * If confirmation passes it will return true, otherwise it will return false.
     *
     * @param  string  $code Confirmation code.
     */
    public function attemptConfirmation($code)
    {
       $model=new Password;
        /** @var Token $token */
        $token = Token::find()->where([
            'user_id' => $this->id,
            'type'    => Token::TYPE_CONFIRMATION,
            'code'    =>$code,
            ])->one();
   
        if ($token === null || $token->isExpired) {
            \Yii::$app->session->setFlash('danger', \Yii::t('app', 'The confirmation link is invalid or expired. Please try requesting a new one.'));
            return false;


        } else {
            $token->delete();
            $hash=$this->generate(6);
            $this->password_hash=$this->setPassword($hash);
            $this->confirmed_at = time();
            $hash=$this->generate(6);

modules/user_management/modules/core/controllers/UserController.php
<?php

namespace app\modules\user_management\modules\core\controllers;

use Yii;
use app\modules\user_management\modules\core\models\User;
use app\modules\user_management\modules\core\models\UserSearch;
use app\modules\user_management\modules\core\models\Guardians;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SocialPluginsController implements the CRUD actions for SocialPlugins model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
       public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if(!isset($model->blocked_at)||($model->blocked_at==null)){
             $model->blocked_at=2;
            }else{
             $model->blocked_at=1;
            }
    
        if ($model->load(Yii::$app->request->post())) {
            if($model->blocked_at==2){
             $model->blocked_at=NULL;
            }else{
               $model->blocked_at=time();
            }
             $model->blocked_at;
            if(isset($model->passwd) && ($model->passwd!='')){
              $model->password_hash=Yii::$app->getSecurity()->generatePasswordHash($model->passwd);
            }
         
              
             if($model->save(false)){
                 $guardian=Guardians::find()->where(['user_id'=>$model->id])->one();
                 if($guardian!==null){
                $guardian->email=$model->email;
                $guardian->save(false);
            }
         
             }
             Yii::$app->session->setFlash('success','User data updated successfully... ');
            return $this->redirect(['/umt.xeo']);
        } else {
            return $this->render('update', [
                'model' => $model,
              
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * actionLoginAs switch users
     * @param integer $id
     * @return mixed
     */
    public function actionLoginAs($key)
    {
        $id=Yii::$app->encryptor->decrypt($key);
        $initialId = Yii::$app->user->getId(); //here is the current ID, so you can go back after that.
        if ($id == $initialId) {
             \Yii::$app->session->setFlash('danger', \Yii::t('app', 'You are already login with this user'));
             return $this->redirect(['/site/index']); //redirect to any page you like.
        } else {
            $user = User::findOne($id);
            $duration = 0;
            Yii::$app->user->switchIdentity($user, $duration); //Change the current user.
            Yii::$app->session->set('user.idbeforeswitch',$initialId); //Save in the session the id of your admin user.
              \Yii::$app->session->setFlash('success', \Yii::t('app', 'You are successfully login as user'));
            return $this->redirect(['/site/index']); //redirect to any page you like.
        }
    }
    
     /**
     * Finds the SocialPlugins model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SocialPlugins the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($key)
    {   
        $id=Yii::$app->encryptor->decrypt($key);
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/user_management/modules/core/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\master_settings\modules\core\models\Usertype;
use kartik\widgets\Select2;
use app\assets\UserAsset;
UserAsset::register($this);
/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

     <?php $form = ActiveForm::begin([
     'options' => ['class' => 'bv-form'],
     'id'      => 'user-form',
     // 'enableAjaxValidation'   => true,
     // 'enableClientValidation' => false,
     'fieldConfig' => [
     'template' => "{label}\n<div class=\"col-xs-8\">{input}{hint}{error}</div>",
     'labelOptions' => ['class' => 'col-sm-4 control-label'],
    ],
     ]); ?>
    <div class="row">
        <div class="col-md-6">
    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'passwd')->textInput(['maxlength' => true]) ?>
    <?php echo $form->field($model, 'user_type')->widget(Select2::classname(), [
            'data' => UserType::getDropDownData(),
            'language' => 'en',
              'options' => ['placeholder' => Yii::t('app','Select Usertype...')],
                'pluginOptions' => [
                 'allowClear' => false
                ],
                //'disabled' => !$model->isNewRecord,
    ]);?>
    <?php echo $form->field($model, 'blocked_at')->widget(Select2::classname(), [
            'data' =>[1=>'block',2=>'unblock'],
            'language' => 'en',
               'options' => ['placeholder' => Yii::t('app','Select Usertype...')],
                'pluginOptions' => [
                   'allowClear' => false
                ],
                //'disabled' => !$model->isNewRecord,
    ])->label('Blocked Status');?>

</div>
</div>
    <div class="form-group btn-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success ' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/user_management/modules/core/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'flag') ?>

  

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'confirmed_at') ?>

    <?php // echo $form->field($model, 'blocked_at') ?>

    <?php // echo $form->field($model, 'registration_ip') ?>

    <?php // echo $form->field($model, 'user_type') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'is_deleted') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/user_management/modules/core/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/user_management/modules/core/views/user/index.php
<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use kartik\widgets\Select2;
use app\modules\master_settings\modules\core\models\Usertype;
use app\modules\settings\modules\core\models\Type;


/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <?php Pjax::begin(); ?>    

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            //'id',
            [
              'label'=>'Type',
              'attribute'=>'types.title',
              'filter' => Select2::widget([
                  'model' => $searchModel,
                  'attribute' => 'type_id',
                  'data' => Type::getDropDownData(),
                  //'initValueText' => $searchModel->citizenship,
                  'options' => [
                      'placeholder' => 'Select Type...'
                  ]
              ]),
               'headerOptions' => ['style' => 'width:20%'],
            ],
          
            [
              'attribute'=>'username',
               'headerOptions' => ['style' => 'width:20%'],
            ],
            [
              'attribute'=> 'email',
               'headerOptions' => ['style' => 'width:40%'],
            ],
           
            // 'password_hash',
            // 'auth_key',
            // 'confirmed_at',
            // 'blocked_at',
            // 'registration_ip',
             [
              'label'=>'User Type',
              'attribute'=>'usertypes.title',
              'filter' => Select2::widget([
                  'model' => $searchModel,
                  'attribute' => 'user_type',
                  'data' => Usertype::getDropDownData(),
                  //'initValueText' => $searchModel->citizenship,
                  'options' => [
                      'placeholder' => 'Select Usertype...'
                  ]
              ]),
               'headerOptions' => ['style' => 'width:20%'],
            ],
            // 'created_at',
            // 'created_by',
            // 'updated_at',
            // 'updated_by',
            // 'status',
            // 'is_deleted',

            ['class' => '\kartik\grid\ActionColumn',
                                        
                  'template' => '{update}&nbsp;{login}',
                    'buttons' => [
                    'login' => function ($url, $model) {
                                  return Html::a('Login As', $url, [
                                    'title' => Yii::t('app', 'Login As '.$model->email.' '),'class'=>'btn btn-xs btn-primary'
                                 ]);
                              }, 
                  ],

                    'urlCreator' => function ($action, $model, $url, $index) {
                         $hash=Yii::$app->encryptor->encrypt($model->id); 
                         if ($action === 'view') {
                            return Url::to(['user/view','id'=>$hash]);
                         }else if($action === 'update'){
                          return Url::to(['user/update','id'=>$hash]);
                         }else if($action === 'delete'){
                          return Url::to(['user/delete','id'=>$hash]);
                         }elseif($action==='login'){
                            return Url::to(['user/login-as','key'=>$hash]);
                         } 
                    },
            ],

        ],

         'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="white fa fa-users "></i> User </h3>',
            'type'=>'primary',
            // 'before'=>Html::a(Yii::t('app', '<i class="glyphicon glyphicon-plus"></i> Create {modelClass}', ['modelClass' => 'AcadamicYear',]), ['create'], ['class' => 'btn btn-primary']) ,
            'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Search', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>true,
            'pager'=>false
          ],
            'toolbar' => [
              //'{export}'
              ],
            'exportConfig' => [
            GridView::HTML =>[],
            //  GridView::PDF =>[],
            GridView::TEXT => [],
            GridView::EXCEL => [],
            ]
    ]); ?>

<?php Pjax::end(); ?>
  
</div>

modules/user_management/modules/core/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">

    <div class="grey panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
			</div>
		<div class="panel-body">

			<div class="col-lg-12">
				<?= $this->render('_form', [
					'model' => $model,
                    
					]) ?>
			</div>
		</div>
	</div>

</div>

modules/user_management/modules/core/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'flag',
          
            'username',
            'email:email',
            'password_hash',
            'auth_key',
            'confirmed_at',
            'blocked_at',
            'registration_ip',
            'user_type',
            'created_at',
            'created_by',
            'updated_at',
            'updated_by',
            'status',
            'is_deleted',
        ],
    ]) ?>

</div>