modules/settings/modules/core/models/Department.php
<?php

namespace app\modules\settings\modules\core\models;

use Yii;
use app\models\BaseModel;

/**
 * This is the model class for table "department".
 *
 * @property integer $id
 * @property string $title
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 * @property integer $is_deleted
 * @property integer $status
 */
class Department extends BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['created_by', 'updated_by', 'is_deleted', 'status'], 'integer'],
            [['title'], 'string', 'max' => 100],
                    //['title', 'required', 'message' => 'Please enter title.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'is_deleted' => Yii::t('app', 'Is Deleted'),
            'status' => Yii::t('app', 'Status'),
        ];
    }
}

modules/settings/modules/core/controllers/DepartmentController.php
<?php

namespace app\modules\settings\modules\core\controllers;

use Yii;
use app\modules\settings\modules\core\models\Department;
use app\modules\settings\modules\core\models\DepartmentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DepartmentController implements the CRUD actions for Department model.
 */
class DepartmentController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Department models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DepartmentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Department model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Department model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Department();

        if ($model->load(Yii::$app->request->post())) {
             $model->save();
            return $this->redirect(['department/index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Department model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['department/index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Department model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Department model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Department the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
  protected function findModel($key)
    { 
        $id=Yii::$app->encryptor->decrypt($key);
        if (($model = Department::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/settings/modules/core/views/department/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Department */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel">
  <div class="panel-body">
  <?php $form = ActiveForm::begin([
  'options' => ['class' => 'form-horizontal bordered-row'],
  'id'                     => 'password-form',
  //'enableAjaxValidation'   => true,
  // 'enableClientValidation' => false,
  'fieldConfig' => [
   'template' => "{label}\n<div class=\"col-xs-9\">{input}{error}</div>",
   'labelOptions' => ['class' => 'col-sm-3 control-label'],
  ],
  ]); ?>
     <div class="row">
        <div class="col-md-6">
        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        </div>
        </div>

        <div class="bg-default content-box text-center pad20A mrg25T col-md-6 col-md-offset-3">
                       <?= Html::a('<i class="ace-icon fa fa-remove"> Cancel</i>', ['department/index'], ['class'=>'btn  btn-danger']);?>
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', '<i class="ace-icon fa fa-plus"> Save</i>') : Yii::t('app', '<i class="ace-icon fa fa-pencil"> Update</i>'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>
     <!--    <div class="col-md-12" style="height: 30px;"></div>
        <div class="form-group">
          <div class="col-md-10 col-md-offset-1">
           
          </div>
        </div>
         <div class="col-md-12" style="height: 10px;"></div>
      </fieldset>  -->
    <?php ActiveForm::end(); ?> 
  </div>
</div>

modules/settings/modules/core/views/department/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DepartmentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="department-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'is_deleted') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/settings/modules/core/views/department/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Department */

$this->title = Yii::t('app', 'Create Department');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Departments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="department-create">

     
        <div class="col-lg-12">
          
<?= $this->render('_form', [
        'model' => $model,
       
        
        
    ]) ?>

</div>
</div>





</div>

modules/settings/modules/core/views/department/index.php
<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ClassesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Department');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="department-index">

<?php Pjax::begin(); ?>   

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],


           
            'title:ntext',
            
            
            // 'updated_at',
            // 'created_by',
            // 'updated_by',
            // 'is_delete',

            ['class' => '\kartik\grid\ActionColumn',
                                        
                  'template' => '{update}&nbsp;{delete}',

'urlCreator' => function ($action, $model, $url, $index) {
                         $hash=Yii::$app->encryptor->encrypt($model->id); 
                         if ($action === 'view') {
                            return Url::to(['department/view','id'=>$hash]);
                         }else if($action === 'update'){
                          return Url::to(['department/update','id'=>$hash]);
                         }else if($action === 'delete'){
                          return Url::to(['department/delete','id'=>$hash]);
                         }
                    },
            ],

        ],
         'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="white fa fa-users "></i> Department </h3>',
            'type'=>'primary',
            'before'=>Html::a(Yii::t('app', '<i class="glyphicon glyphicon-plus"></i> Create {modelClass}', ['modelClass' => 'Department',]), ['create'], ['class' => 'btn btn-primary']) ,
            'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Search', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>true,
            'pager'=>false
            ],
            'toolbar' => [
              //'{export}'
              ],
            'exportConfig' => [
            GridView::HTML =>[],
            //  GridView::PDF =>[],
            GridView::TEXT => [],
            GridView::EXCEL => [],
            ]
    ]); ?>







<?php Pjax::end(); ?></div>




   

modules/settings/modules/core/views/department/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Department */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Department',
]) . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Departments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => Yii::$app->encryptor->encrypt($model->id)]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="department-update">


<div class="grey panel panel-info">
    <div class="panel-heading">
    	  <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
     </div>
    <div class="panel-body">
     
        <div class="col-lg-12">
          
<?= $this->render('_form', [
        'model' => $model,
       
        
        
    ]) ?>
</div>
</div>
</div>


   

</div>

modules/settings/modules/core/views/department/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Department */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Departments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="department-view">

    <h1><?= Html::encode($this->title) ?></h1>

  <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => Yii::$app->encryptor->encrypt($model->id)], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => Yii::$app->encryptor->encrypt($model->id)], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'created_at',
            'created_by',
            'updated_at',
            'updated_by',
            
        ],
    ]) ?>

</div>